version: '3.6'

services:
  kong-database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:0.14.1-alpine
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    image: kong:0.14.1-alpine
    depends_on:
      - kong-database
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    ports:
      - "8000:8000"
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  kong-init:
    build: .
    depends_on:
      - kong-database
      - kong-migration
      - kong
    volumes:
      - ./example:/etc/kong-init/:ro
    command: kong-init --url http://kong:8001 --path /etc/kong-init/kong14.v2.yaml --wait
    environment:
      - RUST_LOG='kong_init=debug'
